/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormGroup: typeof import('./src/components/CrudPage/FormGroup.vue')['default']
    HardDoughnut: typeof import('./src/components/hardmoni/HardDoughnut.vue')['default']
    Index: typeof import('./src/components/CrudPage/Index.vue')['default']
    Index_old: typeof import('./src/components/CrudPage/Index_old.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenShot: typeof import('./src/components/ScreenShot/index.vue')['default']
    ServerBlock: typeof import('./src/components/hardmoni/ServerBlock.vue')['default']
    Table: typeof import('./src/components/CrudPage/Table.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine/TimeLine.vue')['default']
    TimeLineCom: typeof import('./src/components/company/TimeLineCom.vue')['default']
    Toolbar: typeof import('./src/components/ScreenShot/Toolbar/index.vue')['default']
  }
}
